name: SoteSafiri CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # Environment variables...
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_BUCKET_RECEIPTS: ${{ secrets.SUPABASE_BUCKET_RECEIPTS }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      NEXT_PUBLIC_STRIPE_PAYMENT_LINK_YEARLY: ${{ secrets.NEXT_PUBLIC_STRIPE_PAYMENT_LINK_YEARLY }}
      NEXT_PUBLIC_STRIPE_PAYMENT_LINK_MONTHLY: ${{ secrets.NEXT_PUBLIC_STRIPE_PAYMENT_LINK_MONTHLY }}
      GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /login
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /signup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run database migrations
        run: pnpm db:migrate

      - name: Seed database
        run: pnpm db:seed

      - name: Run tests
        run: pnpm test

      - name: Start development server
        run: pnpm dev
